# Site settings
author: Raul Sposito
title: Self.new
header-img: img/home-bg.png
email: raulsposito@gmail.com
copyright_name: Raul Sposito
description: > # this means to ignore newlines until "baseurl:"
  A journey of self-improvement thru code 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  raulsposito

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
